name: Build and Push Docker Images for FastAPI Microservices to ACR

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python and FastAPI dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Build and Push csv_processor_service
      - name: Install dependencies for csv_processor_service
        run: |
          cd csv_processor_service
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Build Docker image for csv_processor_service
        run: |
          cd csv_processor_service
          docker build -t ${{ secrets.ACR_REGISTRY_URL }}/csv_processor_service:latest .

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY_URL }} --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Push Docker image for csv_processor_service to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY_URL }}/csv_processor_service:latest

      # Step 4: Build and Push qg_service
      - name: Install dependencies for qg_service
        run: |
          cd qg_service
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Build Docker image for qg_service
        run: |
          cd qg_service
          docker build -t ${{ secrets.ACR_REGISTRY_URL }}/qg_service:latest .

      - name: Push Docker image for qg_service to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY_URL }}/qg_service:latest

      # Step 5: Build and Push qa_service
      - name: Install dependencies for qa_service
        run: |
          cd qa_service
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Build Docker image for qa_service
        run: |
          cd qa_service
          docker build -t ${{ secrets.ACR_REGISTRY_URL }}/qa_service:latest .

      - name: Push Docker image for qa_service to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY_URL }}/qa_service:latest

      # Step 6: Build and Push DA_Service
      - name: Install dependencies for DA_Service
        run: |
          cd DA_Service
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Build Docker image for DA_Service
        run: |
          cd DA_Service
          docker build -t ${{ secrets.ACR_REGISTRY_URL }}/DA_Service:latest .

      - name: Push Docker image for DA_Service to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY_URL }}/DA_Service:latest
