name: Push Docker Images to Google Artifact Registry

on:
  workflow_dispatch:

jobs:
  push-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate to Google Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_REGISTRY }}

    - name: Build and Push Docker Image for Service 1
      run: |
        cd service1
        docker build -t ${{ secrets.GCP_REGISTRY }}/service1:latest .
        docker push ${{ secrets.GCP_REGISTRY }}/service1:latest

    - name: Build and Push Docker Image for Service 2
      run: |
        cd service2
        docker build -t ${{ secrets.GCP_REGISTRY }}/service2:latest .
        docker push ${{ secrets.GCP_REGISTRY }}/service2:latest

    - name: Build and Push Docker Image for Service 3
      run: |
        cd service3
        docker build -t ${{ secrets.GCP_REGISTRY }}/service3:latest .
        docker push ${{ secrets.GCP_REGISTRY }}/service3:latest

    - name: Build and Push Docker Image for Service 4
      run: |
        cd service4
        docker build -t ${{ secrets.GCP_REGISTRY }}/service4:latest .
        docker push ${{ secrets.GCP_REGISTRY }}/service4:latest
