name: Build and Push Docker Images for FastAPI Microservices to ACR

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker BuildKit (optional for efficient builds)
      - name: Set up Docker BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV 

      # Step 3: Set up Docker Buildx (required for multi-platform support)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Step 4: Build Docker image for csv_processor_service
      - name: Build Docker image for csv_processor_service
        run: |
          cd csv_processor_service
          docker build -t ${{ secrets.ACR_REGISTRY_URL }}/csv_processor_service:latest .

      # Step 5: Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY_URL }} --username ${{ secrets.ACR_USERNAME }} --password-stdin

      # Step 6: Push Docker image for csv_processor_service to ACR
      - name: Push Docker image for csv_processor_service to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY_URL }}/csv_processor_service:latest

      # Step 7: Build and Push qg_service
      - name: Build Docker image for qg_service
        run: |
          cd qg_service
          docker build -t ${{ secrets.ACR_REGISTRY_URL }}/qg_service:latest .

      - name: Push Docker image for qg_service to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY_URL }}/qg_service:latest

      # Step 8: Build and Push qa_service
      - name: Build Docker image for qa_service
        run: |
          cd qa_service
          docker build -t ${{ secrets.ACR_REGISTRY_URL }}/qa_service:latest .

      - name: Push Docker image for qa_service to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY_URL }}/qa_service:latest

      # Step 9: Build and Push DA_Service
      - name: Build Docker image for DA_Service
        run: |
          cd DA_Service
          docker build -t ${{ secrets.ACR_REGISTRY_URL }}/DA_Service:latest .

      - name: Push Docker image for DA_Service to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY_URL }}/DA_Service:latest
