name: Push Docker Images to Google Artifact Registry

on:
  workflow_dispatch:

jobs:
  push-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate to Google Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_REGISTRY }}

    - name: Build and Push Docker Image for Service 1
      run: |
        cd csv_processor_service
        docker build -t ${{ secrets.GCP_REGISTRY }}/csv_processor_service:latest .
        docker push ${{ secrets.GCP_REGISTRY }}/csv_processor_service:latest

    - name: Build and Push Docker Image for Service 2
      run: |
        cd qg_service
        docker build -t ${{ secrets.GCP_REGISTRY }}/qg_service:latest .
        docker push ${{ secrets.GCP_REGISTRY }}/qg_service:latest

    - name: Build and Push Docker Image for Service 3
      run: |
        cd qa_service
        docker build -t ${{ secrets.GCP_REGISTRY }}/service3:latest .
        docker push ${{ secrets.GCP_REGISTRY }}/service3:latest

    - name: Build and Push Docker Image for Service 4
      run: |
        cd DA_Service
        docker build -t ${{ secrets.GCP_REGISTRY }}/DA_Service:latest .
        docker push ${{ secrets.GCP_REGISTRY }}/DA_Service:latest
