name: CI/CD for React App

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_REGISTRY_URL }}/react-app:latest ./rp-frontend

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.ACR_REGISTRY_URL }}/react-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VM_KEY }}

    - name: SSH into Azure VM and Deploy Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.VM_HOST }} << EOF
          docker pull ${{ secrets.ACR_REGISTRY_URL }}/react-app:latest
          docker stop react-app || true
          docker rm react-app || true
          docker run -d --name react-app -p 5000:5000 ${{ secrets.ACR_REGISTRY_URL }}/react-app:latest
        EOF
