name: Deployment for Game_Frontend

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_REGISTRY_URL }}/game_frontend:latest ./game-frontend

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.ACR_REGISTRY_URL }}/game_frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VM_KEY }}

    - name: SSH into Azure VM and Deploy Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.VM_HOST }} << EOF
        # Remove old Docker image if it exists
          docker rmi -f ${{ secrets.ACR_REGISTRY_URL }}/game_frontend:latest || true
          docker pull ${{ secrets.ACR_REGISTRY_URL }}/game_frontend:latest
          docker stop game_frontend || true
          docker rm game_frontend || true
          docker run -d --name kidstube_fe --network my_docker_network --restart always -p 3001:3001 ${{ secrets.ACR_REGISTRY_URL }}/game_frontend:latest
        EOF
