name: Service_deployment

on:
  workflow_dispatch:
    inputs:
      service_choice:
        description: 'Select the service to deploy'
        required: true
        type: choice
        options:
          - csv_processor_service
          - qg_service
          - qa_service
          - da_service
          - fluency_service
          - img_gen_service

jobs:
  setup_vm:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH Agent
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VM_KEY }}

      # Step 3: Install Qdrant and Gentle on the Azure VM
      - name: Install and Run Qdrant and Gentle using Docker
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
            # Update system packages
            sudo apt-get update -y

            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Create Docker network
            docker network create my_docker_network

            # Check if Qdrant is running, if yes, skip, else pull and run it
            if docker ps --filter "name=qdrant" --filter "status=running" | grep -q qdrant; then
              echo "Qdrant is already running, skipping start."
            else
              echo "Starting Qdrant..."
              docker pull qdrant/qdrant:latest
              docker run -d --name qdrant --network my_docker_network --restart always -p 6333:6333 qdrant/qdrant:latest
            fi

            # Check if Gentle is running, if yes, skip, else pull and run it
            if docker ps --filter "name=gentle" --filter "status=running" | grep -q gentle; then
              echo "Gentle is already running, skipping start."
            else
              echo "Starting Gentle..."
              docker pull lowerquality/gentle:latest
              docker run -d --name gentle --network my_docker_network --restart always -p 8765:8765 lowerquality/gentle:latest
            fi
          EOF

  deploy_service:
    runs-on: ubuntu-latest
    needs: setup_vm
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH Agent
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VM_KEY }}

      # Step 3: Set environment variables dynamically based on the selected service
      - name: Set service-specific environment variables
        run: |
          if [[ "${{ github.event.inputs.service_choice }}" == "csv_processor_service" ]]; then
            echo "SERVICE_PORT=8000" >> $GITHUB_ENV
            echo "SERVICE_VOLUME='/home/azureuser:/host_data'" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.service_choice }}" == "qg_service" ]]; then
            echo "SERVICE_PORT=8001" >> $GITHUB_ENV
            echo "SERVICE_VOLUME='/home/azureuser/custom_qg_model_v4.pt:/app/custom_qg_model_v4.pt'" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.service_choice }}" == "qa_service" ]]; then
            echo "SERVICE_PORT=8002" >> $GITHUB_ENV
            echo "SERVICE_VOLUME='/home/azureuser:/host_data'" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.service_choice }}" == "da_service" ]]; then
            echo "SERVICE_PORT=8003" >> $GITHUB_ENV
            echo "SERVICE_VOLUME='/home/azureuser:/host_data'" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.service_choice }}" == "fluency_service" ]]; then
            echo "SERVICE_PORT=8004" >> $GITHUB_ENV
            echo "SERVICE_VOLUME='/home/azureuser:/host_data'" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.service_choice }}" == "img_gen_service" ]]; then
            echo "SERVICE_PORT=7000" >> $GITHUB_ENV
            echo "SERVICE_VOLUME='/home/azureuser/imgModels:/host_data'" >> $GITHUB_ENV
          fi

      # Step 4: Deploy the selected service to Azure VM
      - name: Deploy ${{ github.event.inputs.service_choice }} to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
            # Log in to Azure Container Registry
            echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY_URL }} --username ${{ secrets.ACR_USERNAME }} --password-stdin
          
            # Stop and remove the existing container if running
            docker stop ${{ github.event.inputs.service_choice }} || true
            docker rm ${{ github.event.inputs.service_choice }} || true
          
            # Remove old Docker image if it exists
            docker rmi -f ${{ secrets.ACR_REGISTRY_URL }}/${{ github.event.inputs.service_choice }}:latest || true
          
            # Pull the latest Docker image for the service
            docker pull ${{ secrets.ACR_REGISTRY_URL }}/${{ github.event.inputs.service_choice }}:latest

            # Run the Docker container for the selected service with dynamic port and volume
            docker run -d -p $SERVICE_PORT:$SERVICE_PORT --name ${{ github.event.inputs.service_choice }} --network my_docker_network --restart always -v $SERVICE_VOLUME ${{ secrets.ACR_REGISTRY_URL }}/${{ github.event.inputs.service_choice }}:latest
          EOF
